name: uber
description: Aplicação similar ao Uber.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  firebase_core: ^0.4.4+3
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  google_maps_flutter: ^0.5.28+1
  geolocator: ^5.3.2+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/fundo.png
    - assets/images/logo.png
    - assets/images/motorista.png
    - assets/images/passageiro.png